% Project Euler Problem 2: Even Fibonacci numbers
%
% projecteuler.net
%
% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
%
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
%
% Solution by David Eldon 2016-08-28

range=[1,4e6];

starter=[1,2];

x=starter;

last=x(end);

while last<=range(end)
  x=[x sum(x(end-1:end))];
  last=x(end);
end

x=x(1:end-1);

odd=find((x/2-round(x/2))~=0);

  x(odd)=0;

  sum(x)
